### ISSUE TITLE
Infografia-GregorioOsorioSarmiento

### ISSUE THREAD

**Issue by Gregorio012** [SistemasTecTlaxiaco/actividad-1-infografia-Gregorio012#2]
[Infografia-Modelo de desarrollo de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Gregorio012/files/9420906/Infografia-Modelo.de.desarrollo.de.software.pdf)

**Comment by Elisahadad** [comment]
19.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
